from tkinter import *
root = Tk()
import tkinter.scrolledtext as ScrolledText
root.title("menus")
root.geometry("300x300")
menu1 = Menu(root)
root.config(menu =menu1)
submenu= Menu(menu1)
menu1.add_cascade(label ="file", menu =submenu)
submenu= Menu(menu1)
submenu.add_command(label = "filename")
submenu.add_command(label= "filename")
submenu.add_command(label = "new project")
submenu.add_command(label = "save as")
submenu.add_command(label= "save")
submenu.add_command(label = "settings")
submenu.add_command(label= "Exit")
submenu2 = Menu(menu1)
menu1.add_cascade(label = "edit", menu=submenu2)
submenu2.add_cascade(label = "resizing window")
submenu.add_cascade(label = "back to normal")
submenu3 =Menu(menu1)
menu1.add_cascade(label = "view")
submenu4 = Menu(menu1)
menu1.add_cascade(label="navigate")
submenu5 = Menu(menu1)
menu1.add_cascade(label="code")
submenu6 = Menu(menu1)
menu1.add_cascade(label="help")
root.mainloop()